### ISSUE TITLE
update_vignettes() function

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#56]
@rempsyc 

I think it would be nice to reintegrate the option of rendering vignettes automatically. A very simple and clean design would be to have a separate function called update_vignettes(), which does the following:

1. Search the vignettes folder for qmd or Rmd files.
2. Copy it over to the appropriate location
3. Copy any static images from fig/
4. Render the vignettes
5. Clean up

If the vignette already exists, the file is NOT overwritten (this gives us "freeze" functionality).

If the user wants to overwrite, they must simply delete the rendered vignette. This gives us the ability to overwrite only selected vignettes without having too many arguments.

Alternatively, we could have an overwrite argument which accepts TRUE/FALSE or a vector of file paths.

**Comment by rempsyc** [comment]
Agreed, it has been very troublesome so far to have to edit the `_sidebar.md` file every time I render the website when testing vignettes... This function would strike a balance between convenience (include in script to quickly add vignettes) without changing any default behaviour.

That said vignettes are already rendered and copied to the appropriate location (`docs/`), with images (except for bugs in some cases, fixed in #55 but I'm blocked because I don't know how to correctly specify images in vignettes so they are correctly linked in the rendered website). So steps 1-4 are OK, and some cleanup happens in #55, but more could be done. I think an `overwrite` argument is standard and would be convenient.

So the only thing to do would be to integrate vignettes in `_sidebar.md` (and other website structure-defining files) with `update_vignettes()`. Then it would be easier to continue debugging vignettes in #55 and others...

**Comment by rempsyc** [comment]
Regarding the name of the function, `update_vignettes()` sounds like it will update (modify) existing vignettes. But you are saying that if the vignette already exists, the file is not overwritten (and users perhaps have to delete them manually). So it is not so much about updating vignettes as it is about adding vignettes. So what about `add_vignettes()`? Eventually it would be easy to integrate `add_vignettes()` in the use `use_docsify()` and family directly for convenience (so all is done in one step if desired) also.

**Comment by etiennebacher** [comment]
Just FYI about whether existing vignettes should be overwritten, I originally had a similar idea with an arg `convert_vignettes`, but it turns out that if you "freeze" a vignette then the code in this vignette might be actually broken while it still appears fine on the website. This is why I removed this argument and decided to render all vignettes every time (see section "Major changes" in NEWS of altdoc 0.2.0). Note that rendering all vignettes every time is also the behavior of `pkgdown`. 

I'm following the discussions here from afar, but don't hesitate to ping if needed. And also feel free to add yourselves as contributors in the DESCRIPTION.

**Comment by vincentarelbundock** [comment]
>  it turns out that if you "freeze" a vignette then the code in this vignette might be actually broken due to a package update while it still appears fine on the website. This is why I removed this argument and decided to render all vignettes every time . 

That's a good point I had not thought about. Still, I would love to have a non-default option to freeze because the marginaleffects vignettes take 20 minutes to render, so I can't do it every time.

And if we render them all by default, I think that update_vignettes() would be the better name: users will find it confusing to have slight variations like update_docs() and add_vignettes()

**Comment by rempsyc** [comment]
But we already have a function that does exactly that called `.build_vignettes()`—though it is an internal function. I think it would make sense to use `.build_vignettes()` to build (or update) the vignettes, and then a separate function to update the website to point to the vignettes. So currently vignettes are already being rendered automatically in `docs`, they are just ignored in the website.

So,
1. If the goal is to have the ability to not render vignettes, I think we could simply add an argument `build_vignettes` to the `use_` family of functions;
2. If the goal is also to be able to _separately_ update vignettes without rebuilding the whole site, we could use `build_vignettes()` and make it not internal;
3. If the goal is to have consistency with `update_docs()`, we could create an alias of `build_vignettes()` and call it `update_vignettes()`?

Which begs the question: what name for the separate function to update the site navigation menu to include vignettes?

**Comment by vincentarelbundock** [comment]
I vote for 

update_vignettes()
update_man()
update_navigation()

And then one wrapper which can do them all at once.


Not sure they are all required (you judge), but I have a very strong preference to stick with one naming convention for similar functions.

One thing to consider would be to have a keyword like `$ALTDOCMAN` in the sidebar.yml which gets automatically replaced by an alphabetical list of man pages and/or vignettes.

I'm on my phone so can't activate the review comments.

My only review is that there needs to be an option to only convert exported functions. Currently, a lot of the man/ pages you convert are documented internal functions, which takes forever and will not be displayed on the website.

**Comment by rempsyc** [comment]
Ok, just realized that currently, `update_docs()` also updates vignettes. Whereas, we would like this to be a separate step, presumably. `update_man` would be for references only, so would it replace `update_docs`, or would `update_docs` be the wrapper function which can do them all at once? I also agree to stick with one naming convention. `update_navigation` is a bit ambiguous since it does not specifically refer to vignettes however, unless you are thinking of a sub-argument to specify vignettes, but again besides vignettes this is already done by `update_docs`.

**Comment by vincentarelbundock** [comment]
I just listed function names while walking and on my phone. Maybe we don't need an `update_man()`. I think it's best not to change the current functionality for now, and just add new functionality. So ideally, `update_docs()` would not change much until we've established an overall workflow that we target and have a discussion with Etienne.

For now, you can build all the elements separately, and then we can design an overall function that brings everything together.
